
##internal loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: test
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: test-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: test-app
